# GET http://localhost:8080/polls
# Connection: keep-alive

# POST http://localhost:8080/polls
# Content-Type: application/json

# {
#     "question": "Who will win SuperBowl this year?",
#     "options": [
#         {"value": "New England Patriots"},
#         {"value": "Seattle SeaHawks"},
#         {"value": "Green Bay Packers"},
#         {"value": "Denver Broncos"}        
#     ]
# }

# GET http://localhost:8080/polls/1

# API Documentation
# GET http://localhost:8080/v3/api-docs

# GET http://localhost:8080/swagger-ui/index.html

# DELETE http://localhost:8080/polls/2

# update poll
# PUT http://localhost:8080/polls/1
# Content-Type: application/json

# {
#     "question": "Who will win BasketBall this year?",
#     "options": [
#         {"value": "New England Patriots"},
#         {"value": "Seattle SeaHawks"},
#         {"value": "Green Bay Packers"},
#         {"value": "Denver Broncos"}        
#     ]
# }

# VOTE
# POST http://localhost:8080/polls/1/votes
# Content-Type: application/json

# {
#     "option": {
#         "id": 1,
#         "value": "New England Patriots"
#       }
# }

#  GET http://localhost:8080/polls/1/votes

# Compute results
# GET http://localhost:8080/computeresult?pollId=1
